# Generated by cucumber-sinatra. (2011-07-22 11:54:37 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'src/proman_app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = PromanApp

class PromanAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PromanAppWorld.new
end
